#!/bin/bash
echo "🚀 ANALISI CRYPTO & PORTFOLIO"
echo "============================="
echo ""
echo "📊 PORTAFOGLIO:"
./quantum_commands.sh database | grep -A 10 "STATO DATABASE"
echo ""
echo "🎯 CRYPTO IN MONITORAGGIO:"
echo "• BTCUSDT  - Bitcoin"
echo "• ETHUSDT  - Ethereum"
echo "• SOLUSDT  - Solana" 
echo "• BNBUSDT  - Binance Coin"
echo "• XRPUSDT  - Ripple 🔒 (BLOCCATO)"
echo "• ADAUSDT  - Cardano"
echo ""
echo "📈 ULTIME DECISIONI:"
grep -E ":( HOLD|BUY|SELL)" production.log | tail -6
echo ""
echo "💰 VALORE ATTUALE:"
tail -3 production.log | grep "Portfolio:"
