#!/usr/bin/env python3
print("🔄 GUIDA COMPLETA RIGENERAZIONE API KEYS")
print("="*70)
print("1. 🌐 APRI: https://testnet.binance.vision/")
print("2. 🔐 LOGIN: Usa le tue credenziali Testnet")
print("")
print("3. 🖱️  CLICCA 'API Management' (menu in alto)")
print("")
print("4. 🗑️  SE VECCHIE KEYS ESISTONO:")
print("   - Clicca 'Delete' accanto a ogni key vecchia")
print("   - Conferma l'eliminazione")
print("")
print("5. ➕ CLICCA 'Create API' (pulsante verde)")
print("")
print("6. 📝 COMPILA I CAMPI:")
print("   - Label: 'QuantumTraderUltimate'")
print("   - Description: 'Trading Bot Ultimate System'")
print("")
print("7. ✅ SELEZIONA PERMESSI (IMPORTANTE!):")
print("   - ☑️ Enable Reading (OBBLIGATORIO)")
print("   - ☑️ Enable Spot & Margin Trading (OBBLIGATORIO)")
print("   - ☐ Enable Withdrawals (LASCIA DISABILITATO)")
print("")
print("8. 🔒 CLICCA 'Create'")
print("")
print("9. 📋 COPIA SUBITO (LO VEDI SOLO UNA VOLTA!):")
print("   - API Key: copiala")
print("   - Secret Key: COPIALO SUBITO! Si nasconde dopo")
print("")
print("10. 💾 AGGIORNA IL FILE .env:")
print("")
print("    NANO .ENV:")
print("    BINANCE_TESTNET_API_KEY=la_nuova_api_key_qui")
print("    BINANCE_TESTNET_API_SECRET=il_nuovo_secret_qui")
print("")
print("11. 🧪 TESTA LE NUOVE KEYS:")
print("    python test_api_detailed.py")
print("")
print("12. 🚀 RIAVVIA IL SISTEMA:")
print("    ./run_quantum_final_live.sh")
print("="*70)
print("⚠️  ATTENZIONE: Il Secret Key si NASCONDE dopo la prima visualizzazione!")
print("   📝 Salvalo SUBITO in un file di testo sicuro!")
print("   🔐 Non condividerlo MAI con nessuno!")
